org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
loader_version_range=[1,)

mod_id=riftverse
mod_name=Riftverse: Portals, Rifts & the Multiverse
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.riftverse
mod_authors=Riftverse Team
mod_description=Break the boundaries between universes. Portals, dimensional rifts, cinematic black holes, a Multiverse Hub and procedurally manifested realities.
